# -*- coding: utf-8 -*-
"""
/***************************************************************************
 canvafocus
                                 A QGIS plugin
 Ajuda a saber o centro a janela de mapa
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-11
        copyright            : (C) 2026 by Alberto Rodrigues
        email                : betorodrigues@msn.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load canvafocus class from file canvafocus.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .canva_focus import canvafocus
    return canvafocus(iface)
