# -*- coding: utf-8 -*-
"""
/***************************************************************************
 canvafocusDockWidget
                                 A QGIS plugin
 Ajuda a saber o centro a janela de mapa
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-11
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Alberto Rodrigues
        email                : betorodrigues@msn.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import QEvent, QObject, pyqtSignal, Qt, QTimer
from qgis.PyQt.QtGui import QCursor
from qgis.core import QgsPointXY, QgsWkbTypes
from qgis.gui import QgsRubberBand, QgsVertexMarker
import qgis.utils

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'canva_focus_dockwidget_base.ui'))


class MouseClickInterceptor(QObject):
    borderClicked = pyqtSignal(QgsPointXY)

    def __init__(self, canvas, borderControl):
        super().__init__()
        self.canvas = canvas
        self.borderControl = borderControl
        self.borderClicked.connect(self.centerMap)
        self.canvas.viewport().installEventFilter(self)
        self.active = False

    def eventFilter(self, obj, event):
        if not self.active:
            return super().eventFilter(obj, event)

        if event.type() == QEvent.MouseButtonRelease and obj is self.canvas.viewport():
            point = self.canvas.getCoordinateTransform().toMapCoordinates(event.pos().x(), event.pos().y())
            border_zone = self.borderControl.getBorderZone()

            if not border_zone.contains(point):
                QTimer.singleShot(50, lambda: self.borderClicked.emit(point))
                return True
        return super().eventFilter(obj, event)

    def centerMap(self, point):
        self.canvas.setCenter(point)
        self.canvas.refresh()
        
        centerPoint = self.canvas.viewport().rect().center()
        globalCenterPoint = self.canvas.viewport().mapToGlobal(centerPoint)
        QCursor.setPos(globalCenterPoint)


class canvafocusDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(canvafocusDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
        # Inicializa o controle de borda
        self.borderControl = None
        self.initBorderControl()

    def initBorderControl(self):
        """Inicializa o controle de borda do mapa"""
        canvas = qgis.utils.iface.mapCanvas()
        if not canvas:
            return
            
        # Configura o estilo do botão toggle
        self.toggleButton.setStyleSheet("background-color: red; color: white; border: none;")
        buttonWidth = 24
        self.toggleButton.setFixedWidth(buttonWidth)
        self.toggleButton.setFixedHeight(buttonWidth)
        
        # Cria o controle de borda passando os widgets do UI
        self.borderControl = BorderControl(canvas, self.slider, self.toggleButton)

    def closeEvent(self, event):
        if self.borderControl:
            self.borderControl.cleanup()
        self.closingPlugin.emit()
        event.accept()


class BorderControl:
    def __init__(self, canvas, slider, toggleButton):
        self.canvas = canvas
        self.slider = slider
        self.toggleButton = toggleButton
        
        # Conecta os sinais
        self.slider.valueChanged.connect(self.updateBorder)
        self.toggleButton.toggled.connect(self.toggle)

        self.border = QgsRubberBand(self.canvas, QgsWkbTypes.PolygonGeometry)
        self.border.setColor(Qt.transparent)
        self.border.setWidth(2)
        self.border.setLineStyle(Qt.SolidLine)

        self.center_marker = QgsVertexMarker(self.canvas)
        self.center_marker.setColor(Qt.black)
        if hasattr(QgsVertexMarker, 'ICON_CROSS'):
            self.center_marker.setIconType(QgsVertexMarker.ICON_CROSS)
        elif hasattr(QgsVertexMarker, 'Cross'):
            self.center_marker.setIconType(QgsVertexMarker.Cross)
        elif hasattr(QgsVertexMarker, 'ICON_X'):
            self.center_marker.setIconType(QgsVertexMarker.ICON_X)
        else:
            try:
                self.center_marker.setIconType(1)
            except Exception:
                pass
        self.center_marker.setIconSize(8)
        self.center_marker.setPenWidth(2)
        self.center_marker.setVisible(False)

        self.canvas.extentsChanged.connect(self.updateBorder)

        self.mouseInterceptor = MouseClickInterceptor(self.canvas, self)

    def updateBorder(self):
        if not self.toggleButton.isChecked():
            self.border.reset()
            self.center_marker.setVisible(False)
            return

        self.border.reset()
        extent = self.canvas.extent()
        border_zone = extent.buffered(-min(extent.width(), extent.height()) * (self.slider.value() - 100) / 500)

        self.border.addPoint(QgsPointXY(border_zone.xMinimum(), border_zone.yMinimum()))
        self.border.addPoint(QgsPointXY(border_zone.xMaximum(), border_zone.yMinimum()))
        self.border.addPoint(QgsPointXY(border_zone.xMaximum(), border_zone.yMaximum()))
        self.border.addPoint(QgsPointXY(border_zone.xMinimum(), border_zone.yMaximum()))
        self.border.addPoint(QgsPointXY(border_zone.xMinimum(), border_zone.yMinimum()))

        # desenha cruz no centro da borda
        center_x = (border_zone.xMinimum() + border_zone.xMaximum()) / 2.0
        center_y = (border_zone.yMinimum() + border_zone.yMaximum()) / 2.0
        center_point = QgsPointXY(center_x, center_y)
        self.center_marker.setCenter(center_point)
        self.center_marker.setVisible(True)

    def getBorderZone(self):
        extent = self.canvas.extent()
        return extent.buffered(-min(extent.width(), extent.height()) * (self.slider.value() - 100) / 500)

    def toggle(self, checked):
        self.mouseInterceptor.active = checked
        color = "green" if checked else "red"
        text = "O" if checked else "C"
        self.toggleButton.setText(text)
        self.toggleButton.setStyleSheet(f"background-color: {color}; color: white; border: none;")
        borderColor = Qt.black if checked else Qt.transparent
        self.border.setColor(borderColor)
        self.border.setLineStyle(Qt.DotLine if checked else Qt.SolidLine)
        self.updateBorder()

        if not checked:
            self.border.reset()
            self.center_marker.setVisible(False)

    def cleanup(self):
        """Limpa os recursos quando o widget é fechado"""
        if hasattr(self, 'border'):
            self.border.reset()
        if hasattr(self, 'center_marker'):
            self.center_marker.setVisible(False)
        if hasattr(self, 'mouseInterceptor'):
            self.canvas.viewport().removeEventFilter(self.mouseInterceptor)
